### ISSUE TITLE
No USB ID

### ISSUE THREAD

**Issue by Oleksanderr** [rbino/ems-qart#2]
Hello.
Thank you very much for this soft and drivers.

I followed Step by Step the Readme, but the step 4 doesn't work. 
I tried on 3 computer.
When i open zadig, 0 devices found.
If i click on "list all devices", i can see my unknow devices, but the USB is 0000 0002.

I have no idea about how the fix it. If somebody has an idea, I will be happy the read.

Thank you from France!

**Comment by rbino** [comment]
Do you have the original EMS drivers installed?
If so you have to uninstall them first, Zadig just detects the devices without a driver

**Comment by Oleksanderr** [comment]
Thanks you very much for answer.
I tried on 2 computer wich doesn't have EMS drivers and it's the same problem.

Maybe the problem is from my smart card.

I will post here if I find the solution.

Thanks again.

**Comment by rbino** [comment]
No problem.
If you happen to have a Linux pc or Mac available, try using their version of the program. If it doesn't work either it's probably a problem with your cart (since Linux and Mac versions don't need drivers).
Did the cart work before with other programs?

**Comment by Oleksanderr** [comment]
A friend give me the smart card with LSDJ inside. 
But he put the program into the smart card 3 years ago, So it was working but since he never retry.

I made some loops and I'm affraid to lost everything! lool 
But I will record everything in WAV while I don't have a solution.

I will try with Mac or linux.

Thanks a lot for everything.

**Comment by ghost** [comment]
Hey, just checking in to say I had the same problem, and it's definitely not a defective cart. I tried this on my Win10 laptop and got the exact same thing Oleksanderr described; 0 devices found, hit "List all devices" and got an unknown device with ID 0000 0002.

I tried it again on my Win10 desktop, and it worked just fine.

**Comment by Oleksanderr** [comment]
Ah yes, 
In my case I think this is the card because I tried on 5 differents computer (windows 7/10 mac).

**Comment by rbino** [comment]
@jellypox Zadig is not coded by me, if you have an issue in the detection part of the installation you should [file an issue on their Github project](https://github.com/pbatard/libwdi).  
I'm closing the issue since @Oleksanderr verified that the original problem was a defective cart problem.
