### ISSUE TITLE
Error code?

### ISSUE THREAD

**Issue by donniesteubins** [rbino/ems-qart#5]
I'm not sure if this is an issue with ems-qart or my card, as I can't actually use GB_USB.exe on my computer without getting a blue screen of death. In ems-qart, I keep noticing "EA†EDQ@|††††"--or, if I remove the cr1220 battery, a slightly different code--is the title of bank 1. I am able to pull data off with ems-qart, but attempting to put data on will freeze the program. I have tried just about everything, and could not find any information on what is going on. Could "EA†EDQ@|††††" be some kind of error code? Has anyone mentioned a similar experience while using ems-qart?

**Comment by rbino** [comment]
Hi,  
can you try to execute ems-qart on a different machine (even better if a different OS, like a Linux VM)?

I suspect it's an hardware problem (one of my first carts died soon after I got it just like this, way before I've started developing ems-qart), but I want to be sure.

**Comment by donniesteubins** [comment]
It froze the program on a Windows 10 machine. But, I can't believe it would be a hardware issue. My friend had no issues until he handed it to me, and he was using it less than a week ago.
Do you think that it needs to be reformatted?

**Comment by donniesteubins** [comment]
I get specific errors if I disconnect the card while it is being written to.

This happens when I attempt to write on bank 1:
![ems-3](https://cloud.githubusercontent.com/assets/27236837/24970618/f76f5504-1f82-11e7-9eb8-9750ea0b7f45.PNG)

This happens when I attempt to write on bank 2:
![ems-1](https://cloud.githubusercontent.com/assets/27236837/24970624/fe5bad18-1f82-11e7-94e0-939521580505.PNG)

**Comment by donniesteubins** [comment]
And I can still read the original .gb file from the cart:
![ems-4](https://cloud.githubusercontent.com/assets/27236837/24972306/fe26e924-1f88-11e7-8fc9-61aaadab4415.PNG)

**Comment by rbino** [comment]
Getting those errors if you disconnect from the cart while writing is normal, but the fact that, when you disconnect, the program is still writing at the first address is probably an indication of the fact that write commands just hang, probably indicating an hardware problem.

The only way to be sure would be trying to write with
- A different OS or
- The official program or
- Same OS and program but a different cart

Sadly the fact that your friend didn't have hardware issues it's not enough to exclude an hardware problem, everything it's working until it's not

**Comment by rbino** [comment]
@donniesteubins have you tried some of the things I've written above? Otherwise I would close this as hardware problem.
