### ISSUE TITLE
Not working on Win10

### ISSUE THREAD

**Issue by Cosmoledo** [rbino/ems-qart#7]
The version of ems-qart_v0.9.4 does not work on Win10 Pro x64.

Driver installing with zadig-2.3 worked without an error. In the Windows Device Manager is the EMS Cart listed as known. No errors or visible wrong things.

Opening the ems-qart shows the red dot and "cart not connected".

If have done many reboots. The same procedure i have done worked on a Win7 without problems.

Log of zadig:
[zadig.txt](https://github.com/rbino/ems-qart/files/1142517/zadig.txt)

**Comment by rbino** [comment]
Did you use the included Zadig 2.2 or the new Zadig 2.3? I haven't tested it yet with the new version

**Comment by Cosmoledo** [comment]
I have used Zadig 2.2 AND Zadig 2.3. Both said everything worked fine. But ems-qart says cart not found. The log is from Zadig 2.3.

**Comment by Cosmoledo** [comment]
Any solutions?

**Comment by rbino** [comment]
Sadly I currently don't have a Windows 10 environment to debug this problem, so you'll have to wait a bit until I bring it back.

If you have new informations (for example, try checking under "Devices and hardware" if the cart is correctly displayed using Zadig as a driver) post it here please.

**Comment by Cosmoledo** [comment]
No problem, because it still works at Win7 :)

**Comment by ghost** [comment]
Tried to install it on W10 1703. Same problem that Cosmoledo mentions. After Zadig 2.3 says installation went fine but ems-qart doesn't pick up the cart. It now shows in the Device administrator as "Unknown Device #1"

**Comment by shinmai** [comment]
Don't know if any work has went into this issue since it was reported, but testing on Win10 10.0.17134 Build 17134 today, everything worked perfect. Replaced driver with WinUSB using Zadig, disconnected and reconnected cart and launched ems-qart and it detected the cart.

**Comment by Cosmoledo** [comment]
Okay, I will try it again today

**Comment by Cosmoledo** [comment]
It does work with ems-qart_v0.9.4 and zadig 2.4 on Windows 10 Version 1703 Build 15063.1387
